# To Organize all similar Patriot Properties Mappings
# Formulas made in the county tracker to copy and paste long mapping list

PATRIOT_URL_MAPPING = {
    "FalmouthMA": "https://falmouth.patriotproperties.com/default.asp",
    "DoverMA": "https://dover.patriotproperties.com/default.asp",
    "AcushnetMA": "https://acushnet.patriotproperties.com",
    "AgawamMA": "https://agawam.patriotproperties.com",
    "AndoverMA": "https://andover.patriotproperties.com",
    "ArlingtonMA": "https://arlington.patriotproperties.com",
    "AshfieldMA": "https://ashfield.patriotproperties.com",
    "AuburnME": "https://auburnmaine.patriotproperties.com",
    "BarnardVT": "https://barnardvt.patriotproperties.com",
    "BartonVT": "https://bartonvt.patriotproperties.com",
    "BedfordMA": "https://bedford.patriotproperties.com",
    "BelchertownMA": "https://belchertown.patriotproperties.com",
    "BellinghamMA": "https://bellingham.patriotproperties.com",
    "BeverlyMA": "https://beverly.patriotproperties.com",
    "BillericaMA": "https://billerica.patriotproperties.com",
    "BlandfordMA": "https://blandford.patriotproperties.com",
    "BraintreeMA": "https://braintree.patriotproperties.com",
    "BrentwoodNH": "https://brentwoodnh.patriotproperties.com",
    "BrimfieldMA": "https://brimfield.patriotproperties.com",
    "BurlingtonMA": "https://burlington.patriotproperties.com",
    "CarlisleMA": "https://carlisle.patriotproperties.com",
    "CastletonVT": "https://castletonvt.patriotproperties.com",
    "CharltonMA": "https://charlton.patriotproperties.com",
    "ClarksburgMA": "https://clarksburg.patriotproperties.com",
    "CohassetMA": "https://cohasset.patriotproperties.com",
    "CoventryVT": "https://coventryvt.patriotproperties.com",
    "CummingtonMA": "https://cummington.patriotproperties.com",
    "DaltonMA": "https://dalton.patriotproperties.com",
    "DanversMA": "https://danvers.patriotproperties.com",
    "DeerfieldMA": "https://deerfield.patriotproperties.com",
    "DerbyVT": "https://derbyvt.patriotproperties.com",
    "DouglasMA": "https://douglas.patriotproperties.com",
    "DunstableMA": "https://dunstable.patriotproperties.com",
    "EssexMA": "https://essex.patriotproperties.com",
    "EverettMA": "https://everett.patriotproperties.com",
    "FairhavenMA": "https://fairhaven.patriotproperties.com",
    "Fall RiverMA": "https://fallriver.patriotproperties.com",
    "FraminghamMA": "https://framingham.patriotproperties.com",
    "FranklinMA": "https://franklin.patriotproperties.com",
    "Great BarringtonMA": "https://greatbarrington.patriotproperties.com",
    "GrovelandMA": "https://groveland.patriotproperties.com",
    "HamiltonMA": "https://hamilton.patriotproperties.com",
    "HardwickMA": "https://hardwick.patriotproperties.com",
    "HatfieldMA": "https://hatfield.patriotproperties.com",
    "HaverhillMA": "https://haverhill.patriotproperties.com",
    "HolbrookMA": "https://holbrook.patriotproperties.com",
    "HolyokeMA": "https://holyoke.patriotproperties.com",
    "HopedaleMA": "https://hopedale.patriotproperties.com",
    "HopkintonMA": "https://hopkinton.patriotproperties.com",
    "HullMA": "https://hull.patriotproperties.com",
    "IpswichMA": "https://ipswich.patriotproperties.com",
    "JamaicaVT": "https://jamaicavt.patriotproperties.com",
    "JayVT": "https://jayvt.patriotproperties.com",
    "Lancaster CountySC": "https://lancastercountysc.patriotproperties.com",
    "LeicesterMA": "https://leicester.patriotproperties.com",
    "LittletonMA": "https://littleton.patriotproperties.com",
    "LynnMA": "https://lynn.patriotproperties.com",
    "LynnfieldMA": "https://lynnfield.patriotproperties.com",
    "MaldenMA": "https://malden.patriotproperties.com",
    "Manchester-by-the-SeaMA": "https://manchester.patriotproperties.com",
    "MarbleheadMA": "https://marblehead.patriotproperties.com",
    "MarshfieldMA": "https://marshfield.patriotproperties.com",
    "MarshfieldVT": "https://marshfieldvt.patriotproperties.com",
    "MaynardMA": "https://maynard.patriotproperties.com",
    "MedwayMA": "https://medway.patriotproperties.com",
    "MelroseMA": "https://melrose.patriotproperties.com",
    "MerrimacMA": "https://merrimac.patriotproperties.com",
    "MethuenMA": "https://methuen.patriotproperties.com",
    "MiddletonMA": "https://middleton.patriotproperties.com",
    "MilfordMA": "https://milford.patriotproperties.com",
    "MillvilleMA": "https://millville.patriotproperties.com",
    "MiltonMA": "https://milton.patriotproperties.com",
    "MontagueMA": "https://montague.patriotproperties.com",
    "MontgomeryMA": "https://montgomery.patriotproperties.com",
    "MontpelierVT": "https://montpeliervt.patriotproperties.com",
    "NahantMA": "https://nahant.patriotproperties.com",
    "New AshfordMA": "https://newashford.patriotproperties.com",
    "NewburyMA": "https://newbury.patriotproperties.com",
    "North AdamsMA": "https://northadams.patriotproperties.com",
    "North AndoverMA": "https://northandover.patriotproperties.com",
    "NorthboroughMA": "https://northborough.patriotproperties.com",
    "NorthfieldMA": "https://northfield.patriotproperties.com",
    "NorwichVT": "https://norwichvt.patriotproperties.com",
    "OrangeMA": "https://orange.patriotproperties.com",
    "PembrokeMA": "https://pembroke.patriotproperties.com",
    "PepperellMA": "https://pepperell.patriotproperties.com",
    "PeruMA": "https://peru.patriotproperties.com",
    "PlainvilleMA": "https://plainville.patriotproperties.com",
    "PlymouthMA": "https://plymouth.patriotproperties.com",
    "RaynhamMA": "https://raynham.patriotproperties.com",
    "ReadingMA": "https://reading.patriotproperties.com",
    "RevereMA": "https://revere.patriotproperties.com",
    "RochesterNH": "https://rochesternh.patriotproperties.com",
    "SalemMA": "https://salem.patriotproperties.com",
    "SalisburyMA": "https://salisbury.patriotproperties.com",
    "SaugusMA": "https://saugus.patriotproperties.com",
    "ShelburneMA": "https://shelburne.patriotproperties.com",
    "SherbornMA": "https://sherborn.patriotproperties.com",
    "ShirleyMA": "https://shirley.patriotproperties.com",
    "SomersworthNH": "https://somersworthnh.patriotproperties.com",
    "SouthboroughMA": "https://southborough.patriotproperties.com",
    "SpringfieldVT": "https://springfieldvt.patriotproperties.com",
    "StonehamMA": "https://stoneham.patriotproperties.com",
    "StoughtonMA": "https://stoughton.patriotproperties.com",
    "SwampscottMA": "https://swampscott.patriotproperties.com",
    "TollandMA": "https://tolland.patriotproperties.com",
    "TopsfieldMA": "https://topsfield.patriotproperties.com",
    "TownsendMA": "https://townsend.patriotproperties.com",
    "TyngsboroughMA": "https://tyngsborough.patriotproperties.com",
    "UptonMA": "https://upton.patriotproperties.com",
    "UxbridgeMA": "https://uxbridge.patriotproperties.com",
    "WakefieldMA": "https://wakefield.patriotproperties.com",
    "WalthamMA": "https://waltham.patriotproperties.com",
    "WarwickMA": "https://warwick.patriotproperties.com",
    "WatertownMA": "https://watertown.patriotproperties.com",
    "WendellMA": "https://wendell.patriotproperties.com",
    "WenhamMA": "https://wenham.patriotproperties.com",
    "West BridgewaterMA": "https://westbridgewater.patriotproperties.com",
    "West NewburyMA": "https://westnewbury.patriotproperties.com",
    "West TisburyMA": "https://westtisbury.patriotproperties.com",
    "WestboroughMA": "https://westborough.patriotproperties.com",
    "WestfordMA": "https://westford.patriotproperties.com",
    "WhitmanMA": "https://whitman.patriotproperties.com",
    "WilliamsburgMA": "https://williamsburg.patriotproperties.com",
    "WilliamstownMA": "https://williamstown.patriotproperties.com",
    "WinchesterMA": "https://winchester.patriotproperties.com",
    "WorthingtonMA": "https://worthington.patriotproperties.com"
}